package com.visualu.hdf5struct.cmpd;

import java.util.List;

public class ChannelLocations {
    private String labels;
    private String type;
    private double theta;
    private double radius;
    private double X;
    private double Y;
    private double Z;
    private double sph_theta;
    private double sph_phi;
    private double sph_radius;
    private double urchan;
    private String ref;

    public ChannelLocations(String labels, String type, double theta,
                            double radius, double X, double Y, double Z,
                            double sph_theta, double sph_phi,
                            double sph_radius, double urchan, String ref) {
        this.labels = labels;
        this.type = type;
        this.theta = theta;
        this.radius = radius;
        this.X = X;
        this.Y = Y;
        this.Z = Z;
        this.sph_theta = sph_theta;
        this.sph_phi = sph_phi;
        this.sph_radius = sph_radius;
        this.urchan = urchan;
        this.ref = ref;
    }

    /**
     * Static method to generate an array of ChannelLocations from a List of
     * attribute values, such as one returned by getCompoundData.
     * @param list the list of attribute values
     * @return an array of ChannelLocations objects generated by list
     */
    static public ChannelLocations[] fromList(List list) {
        // assume all the arrays are the same size
        int count = ((Object []) list.get(0)).length;

        ChannelLocations[] cls = new ChannelLocations[count];
        for (int i = 0; i < count; i++) {
            cls[i] = new ChannelLocations(
                ((String[]) list.get(0))[i], ((String[]) list.get(1))[i],
                ((double[]) list.get(2))[i], ((double[]) list.get(3))[i],
                ((double[]) list.get(4))[i], ((double[]) list.get(5))[i],
                ((double[]) list.get(6))[i], ((double[]) list.get(7))[i],
                ((double[]) list.get(8))[i], ((double[]) list.get(9))[i],
                ((double[]) list.get(10))[i], ((String[]) list.get(11))[i]);
        }
        return cls;
    }

    /**
     * Summarizes the object
     * @return a decent String
     */
    public String toString() {
        return "ChannelLocations{labels=" + this.labels + ",type=" + this.type +
            ",theta=" + this.theta + ",radius=" + this.radius +
            ",X=" + this.X + ",Y=" + this.Y + ",Z=" + this.Z +
            ",sph_theta=" + this.sph_theta + ",sph_phi=" + this.sph_phi +
            ",sph_radius=" + this.sph_radius + ",urchan=" + this.urchan +
            ",ref=" + this.ref + "}";
    }
}
